child_behaviour_analysis/childApp/urls.py
from django.conf.urls import url
from childApp import views
from django.urls import path

app_name = 'childApp'

urlpatterns = [
    path('', views.dataUploadView.as_view(), name='child'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    #path('result', views.finalresult.as_view(), name= 'result'),
    #path('success', views.Success.as_view(), name = 'success'),
    #path('fail',views.Failure.as_view(),name='fail'),
    #path('filenot',views.FileNotfound.as_view(), name='filenot'),
    #path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

child_behaviour_analysis/child_behaviour_analysis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from childApp import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/',include('childApp.urls',namespace='childApp')),
    #path('', views.FileUploadView.as_view(), name = 'image_upload'),
    #path('whats', views.WhatsappAnalaysis.as_view(), name = 'whats'),
    path('', views.dataUploadView.as_view(), name= 'child'),
    #path('success', views.Success.as_view(), name = 'success'),
    #path('fail',views.Failure.as_view(),name='fail'),
    #path('filenot',views.FileNotfound.as_view(), name='filenot'),
    #path('aboutus',views.AboutUs.as_view(), name='aboutus')
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

child_behaviour_analysis/childApp/models.py
from django.db import models

# Create your models here.
class childModel(models.Model):
    # MOOD_CHOICES = [
    #     ('Happy', 'Happy'),
    #     ('Sad', 'Sad'),
    #     ('Neutral', 'Neutral'),
    # ]
    # Mood = models.CharField(max_length=20, choices=MOOD_CHOICES)
    # Blood_Urea=models.FloatField()
    # Serum_Creatine=models.FloatField()
    # Packed_cell_volume=models.FloatField()
    # White_blood_count=models.FloatField()
    # Age = models.FloatField()
    Play_Hours = models.FloatField()
    Screen_Time = models.FloatField()
    Study_Hours = models.FloatField()
    Meals_Per_Day = models.FloatField()
    Sleep_Hours = models.FloatField()

child_behaviour_analysis/childApp/forms.py
# from django import forms
# from .models import *
#
#
# class childInfoForm(forms.ModelForm):
#     class Meta():
#         model = childModel
#         fields = '__all__'
#         widgets = {
#             'Mood': forms.Select(attrs={'class': 'form-control'}),
#             'Screen_Time': forms.NumberInput(attrs={'class': 'form-control'}),
#             'Study_Hours': forms.NumberInput(attrs={'class': 'form-control'}),
#             'Meals_Per_Day': forms.NumberInput(attrs={'class': 'form-control'}),
#             'Sleep_Hours': forms.NumberInput(attrs={'class': 'form-control'}),
#         }
#         # fields = ['Mood', 'Screen_Time', 'Study_Hours', 'Meals_Per_Day', 'Sleep_Hours']


from django import forms
from .models import *

class childInfoForm(forms.ModelForm):
    class Meta:
        model = childModel
        fields = '__all__'
        widgets = {
            # 'mood': forms.Select(attrs={'class': 'form-control'}),
            'Play_Hours': forms.NumberInput(attrs={'class': 'form-control'}),
            'Screen_Time': forms.NumberInput(attrs={'class': 'form-control'}),
            'Study_Hours': forms.NumberInput(attrs={'class': 'form-control'}),
            'Meals_Per_Day': forms.NumberInput(attrs={'class': 'form-control'}),
            'Sleep_Hours': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(childInfoForm, self).__init__(*args, **kwargs)
        # Replace '----' with 'Select Mood'
        # self.fields['Mood'].choices = [('', 'Select Mood')] + list(self.fields['Mood'].choices)[1:]

child_behaviour_analysis/childApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
#from .forms import *
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView)
from . import models
from .forms import *
import joblib
import pickle
from django.core.files.storage import FileSystemStorage
#from topicApp.Topicfun import Topic
#from ckdApp.funckd import ckd
#from sklearn.tree import export_graphviz #plot tree
#from sklearn.metrics import roc_curve, auc #for model evaluation
#from sklearn.metrics import classification_report #for model evaluation
##from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(df2.drop('classification_yes', 1), df2['classification_yes'], test_size = .2, random_state=10)

import time
import pandas as pd
import numpy as np
#from sklearn.preprocessing import StandardScaler
#from sklearn.feature_selection import SelectKBest
#from sklearn.feature_selection import chi2
#from sklearn.model_selection import train_test_split
#from sklearn.decomposition import PCA
#from sklearn.feature_selection import RFE
#from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
#import eli5 #for purmutation importance
#from eli5.sklearn import PermutationImportance
#import shap #for SHAP values
#from pdpbox import pdp, info_plots #for partial plots
np.random.seed(123) #ensure reproduc
class dataUploadView(View):
    form_class = childInfoForm
    success_url = reverse_lazy('success')
    template_name = 'create.html'
    failure_url = reverse_lazy('fail')
    filenot_url = reverse_lazy('filenot')
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        #print('inside post')
        form = self.form_class(request.POST, request.FILES)
        #print('inside form')
        if form.is_valid():
            form.save()
            playHours = request.POST.get('Play_Hours')
            screenTime = request.POST.get('Screen_Time')
            studyHours = request.POST.get('Study_Hours')
            mealsPerDay = request.POST.get('Meals_Per_Day')
            sleepHours = request.POST.get('Sleep_Hours')

            model = joblib.load('childmodel.pkl')
            scaler = joblib.load('scaler1.pkl')
            label_encoders = joblib.load('label_encoders1.pkl')

            # # 3. Encode categorical value
            # valid_moods = label_encoders['Mood'].classes_
            # if data_bgr not in valid_moods:
            #     return render(request, "error.html", {
            #         "message": f"Invalid mood: '{data_bgr}'. Please choose from: {', '.join(valid_moods)}"
            #     })

            # mood_encoded = label_encoders['Mood'].transform([mood])[0]
            # mood_encoded = label_encoders['Mood'].transform([data_bgr])[0]

            # 4. Prepare input in correct order
            input_data = np.array([[playHours, screenTime, studyHours, mealsPerDay, sleepHours]])

            # 5. Scale input
            scaled_input = scaler.transform(input_data)

            # 6. Predict
            prediction = model.predict(scaled_input)[0]
            predicted_label = label_encoders['Behavior_Category'].inverse_transform([prediction])
            # #print (data)
            # #dataset1=pd.read_csv("prep.csv",index_col=None)
            # dicc={'yes':1,'no':0}
            # filename = 'finalized_model_ckd.sav'
            # classifier = pickle.load(open(filename, 'rb'))
            #
            # data = np.array([data_bgr,data_bu,data_sc,data_pcv,data_wc])
            # #sc = StandardScaler()
            # #data = sc.fit_transform(data.reshape(-1,1))
            # out=classifier.predict(data.reshape(1,-1))
# providing an index
            #ser = pd.DataFrame(data, index =['bgr','bu','sc','pcv','wbc'])

            #ss=ser.T.squeeze()
#data_for_prediction = X_test1.iloc[0,:].astype(float)

#data_for_prediction =obj.pca(np.array(data_for_prediction),y_test)
            #obj=ckd()
            ##plt.savefig("static/force_plot.png",dpi=150, bbox_inches='tight')
            return render(request, "succ_msg.html", {'playHours':playHours,'screenTime':screenTime,'studyHours':studyHours,'mealsPerDay':mealsPerDay,'sleepHours':sleepHours,
                                                        'out':predicted_label})


        else:
            return redirect(self.failure_url)

child_behaviour_analysis/childApp/templates/aboutus.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to Analysis World</h1>
      <p>Here you can Analysis your whatsapp chat</p>
    </div>

{% endblock %}

child_behaviour_analysis/childApp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Child Behaviour App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <!-- Custom Fonts & Icons -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <style>
    body {
      font-family: 'Poppins', sans-serif;
      background-image: url("{% static 'output_image/background.PNG' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
      backdrop-filter: blur(4px);
      color: #333;
    }

    .navbar-default {
      background-color: #00796b;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .navbar-brand,
    .nav-link {
      font-weight: 500;
      font-size: 1.1rem;
    }

    .container {
      background-color: rgba(255, 255, 255, 0.9);
      margin-top: 30px;
      padding: 30px;
      border-radius: 16px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
    }

    h1, h2, h3 {
      font-weight: 700;
    }

    footer {
      margin-top: 40px;
      text-align: center;
      font-size: 0.9rem;
      color: #666;
    }
  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-sm navbar-default navbar-dark">
    <a class="navbar-brand" href="{% url 'childApp:child' %}"><i class="fas fa-child"></i> Child Behaviour</a>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'childApp:child' %}"><i class="fas fa-home"></i> Home</a>
      </li>
    </ul>
  </nav>

  <!-- Main Container -->
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

  <footer>
    <p>&copy; a2025 Child Behaviour Predictor. All rights reserved.</p>
  </footer>

</body>
</html>

child_behaviour_analysis/childApp/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<div>
    <div class="card-header bg-info text-white text-center">
      <h2>🧒 Child Behaviour Predictor</h2>
      <p class="mb-0">Please fill out the form to analyze your child's behavior (age under 15)</p>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <div class="text-center mt-3">
          <button type="submit" class="btn btn-success btn-lg">🔍 Predict Behavior</button>
        </div>
      </form>
    </div>
</div>

{% endblock %}


child_behaviour_analysis/childApp/templates/fail.html
{% extends 'base.html' %}

{% block body-content %}
{% load staticfiles %}

    <h1>Please upload Whatsapp .Text file</h1>
    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
{% endblock %}

child_behaviour_analysis/childApp/templates/filenot.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Please rename your file name</h1>
  </body>
</html>

child_behaviour_analysis/childApp/templates/out.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="jumbotron">


<h1>Topic Modelling</h1>
<br>
  {% for i,index ,topic in topiresult.itertuples %}
    {{index}}:{{topic}}
<br>
  {%endfor%}

<h1>Sentimental Report and Wordcloud</h1>

      <h2>Echo_ White</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Echo_White.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Echo_White.PNG' %}"/>
      <br>
      <h2>Fire 8 HD</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Fire8HD.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Fire8HD.PNG' %}"/>
      <br>
      <h2>Fire Tablet for kids 7</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_Firekids7.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_Firekids7.PNG' %}"/>
      <br>
      <h2>FireTV</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_FireTV.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_FireTV.PNG' %}"/>
      <br>
      <h2>Fire Table 7</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_FireTablet_7.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_FireTablet_7.PNG' %}"/>
      <br>
      <h2>Kindle Fire 10</h2>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'sentimental_image/sentiment_KindelFire10.png' %}"/>
      <br>
      <img  class="mx-auto d-block" style="width: 900px; height: 450px" alt="Date_ Chart" src= "{% static 'wordcloudimage/wordcloud_KindelFire10.PNG' %}"/>
      <br>

{%endblock%}
</div>

child_behaviour_analysis/childApp/templates/predictor/input.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
    body {
      background-image: url("{% static 'output_image/background.PNG' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100% 100%;
          }
    .navbar-default {
    background-color: #075E54;
    border-color: #030033;
}

    </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-default navbar-dark">
  <!-- Brand -->
      <a class="navbar-brand" href="{% url 'childApp:child' %}">Home</a>

      <!-- Links -->
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'childApp:child' %}">Child APP</a>
        </li>

      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>

</html>

child_behaviour_analysis/childApp/templates/predictor/output.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="jumbotron">
    <h1>Chronic Kidney Disease </h1>
    <div class="fieldWrapper">
      <h2>For the values</h2>
      <p>Blood_Glucose_Random:{{data_bgr}}</p>
      <p>Blood_Urea:{{data_bu}}</p>
      <p>Serum_Creatine:{{data_sc}}</p>
      <p>Packed_cell_volume:{{data_pcv}}</p>
      <p>White_blood_count:{{data_wc}}</p>
      <p>OUTPUT::{{out}}</p>
      
    
    <a  href="{% url 'childApp:child' %}">Child Predicition</a>
    <br>
</div>
{% endblock %}

child_behaviour_analysis/childApp/templates/process.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}
<div class="">
  <br>
  <br>
</div>
<table class="table table-dark table-striped table-left" align="left">
            <tr>
              <th>Sl.No</th>
              <th>Date</th>
              <th>Time</th>
              <th>Text</th>
              <th>Name</th>
              <th>Scores</th>
              <th>compound</th>
              <th>Negetive</th>
              <th>Positive</th>
              <th>Netural</th>
              <th>comp_score</th>
              <th>Topic</th>
            </tr>
            {% for slno,date,time,text,name,scores,compound,negetive,positive, neutral,compscore,topic in dataset.itertuples %}


            <tr>
              <td>{{slno}}</td>
              <td> {{date}}</td>
              <td>{{time}}</td>
              <td>{{text}} </td>
              <td>{{name}}</td>
              <td>{{scores}}</td>
              <td>{{compound}}</td>
              <td>{{negetive}}</td>
              <td>{{positive}}</td>
              <td>{{neutral}}</td>
              <td>{{compscore}}</td>
              <td>{{topic}}</td>
            </tr>

            {% endfor%}

      </table>

{% endblock %}

child_behaviour_analysis/childApp/templates/ref.html
{% extends 'base.html' %}

{% block body_block %}
{% load staticfiles %}
<div class="jumbotron">
    <h1>Well Done!! </h1>
    <div class="fieldWrapper">
    <p><strong>Talkative</strong>: {{result.0}}</p>
    <p><strong>Less Talkative</strong>: {{result.1}}</p>
    {% if not result1 %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.0}}: {{result.2}}</p>
    {% endif %}
    {% if not result1  %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: Wonderfull No Filrting</p>
    {% else %}
      <p><strong>Filrt Percentage by </strong> {{result.1}}: {{result.3}}</p>
    {% endif %}
    <p><strong>Most Active Date</strong>: {{stats.0}}</p>
    <p><strong>Most Active Day</strong>: {{stats.1}}</p>
    <p><strong>Most Active Hour</strong>: {{stats.2}}</p>
    <p><strong>Average Number of Message per Day</strong>: {{stats.3}}</p>
    <p><strong>Media Shared Freak</strong>: {{stats1.0}}</p>
    <p><strong>Message Deleted Freak</strong>: {{stats1.1}}</p>
    <p><strong>Missed Voice Call Count</strong>: {{stats1.2}}</p>
    <p><strong>Missed Video Call Count</strong>: {{stats1.3}}</p>
    <p>DateWise Message Count</p>
    <img src="date_chart.png" alt="Date_Chart">
    {% if media_count == "No Media were shared" %}
      <p><strong>Media Count</strong>: {{media_count}}</p>
    {% else %}
      <p><strong>Media Count</strong>
        <img src="media_count.png" alt="media_count">
    {% endif %}
    {% if msg_deleted_count == "No message was deleted" %}
      <p><strong>Deleted message Count</strong>: {{msg_deleted_count}}</p>
    {% else %}
      <p><strong>Deleted message Count</strong>:</p>
      <img src="msg_deleted_count.png" alt="msg_deleted_count">
    {% endif %}
    {% if voice_call_count == "No Missed Voice Call" %}
      <p><strong>Missed Voice Call Count:</strong>: {{voice_call_count}}</p>
    {% else %}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="voice_call_count.png" alt="voice_call_count">
    {% endif %}
    {% if video_call_count == "No Missed Video Call"%}
      <p><strong>Missed Video Call Count:</strong>: {{video_call_count}}</p>
    {%else%}
      <p><strong>Missed Voice Call Count:</strong>:</p>
      <img src="video_call_count.png" alt="video_call_count">
    {% endif %}
    </div>

    <a  href="{% url 'app_uplaod:image_upload' %}">Upload_TextFile</a>
</div>
{% endblock %}

child_behaviour_analysis/childApp/templates/succ_msg.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}

<div>
  <div class="card shadow-lg">
    <div class="card-header" style="background-color: #e8f5e9; color: #2e7d32;">
        <h2 class="text-center">🎯 Child Behaviour Analysis Result</h2>
    </div>
    <div class="card-body">
      <h4 class="mb-4 text-success">✨ Prediction based on the following inputs:</h4>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Play Hours of the Kiddo(in hours):</strong> {{playHours}}</li>
        <li class="list-group-item"><strong>Daily Screen Time (in hours):</strong> {{screenTime}}</li>
        <li class="list-group-item"><strong>Study Time Per Day (in hours):</strong> {{studyHours}}</li>
        <li class="list-group-item"><strong>Number of Meals per Day:</strong> {{mealsPerDay}}</li>
        <li class="list-group-item"><strong>Sleep Duration per Night (in hours):</strong> {{sleepHours}}</li>
      </ul>

      <div class="alert alert-info mt-4" role="alert">
        <h5><strong>Predicted Behaviour:</strong> <span class="text-dark">{{out}}</span></h5>
      </div>

      <div class="text-center mt-4">
        <a href="{% url 'childApp:child' %}" class="btn btn-outline-primary btn-lg">🔁 Try Another Prediction</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}